### ISSUE TITLE
Crashes if connection to Discord is lost

### ISSUE THREAD

**Issue by JakeStanger** [JakeStanger/mpd-discord-rpc#10]
If Discord restarts or the connection to its RPC server drops for whatever reason, the program crashes.

```
thread '<unnamed>' panicked at 'Failed to send outgoing data: IoError(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/discord-rpc-client-0.3.0/src/connection/manager.rs:131:30
```

**Comment by emersonrp** [comment]
My Discord crashes every time I sleep/wake the computer, and occasionally for no good reason whatsoever, so I run into this a lot.

**Comment by JakeStanger** [comment]
It looks like the underlying `discord-presence` crate doesn't surface the connection errors very well, so I'll open an issue there.

**Comment by JakeStanger** [comment]
The above has been fixed and the library updated, so this is now resolved on `master` here.

I have noticed however that the connection retry logic in the library currently has no chill and really spams the socket/log, so I'm waiting for https://github.com/jewlexx/discord-presence/pull/73 to be merged before getting a release out or closing this.

**Comment by emersonrp** [comment]
I've managed to fix my Discord crashing on sleep/wake, which is itself a huge win, but yeah at boot time I think the systemd service starts before Discord so needs to be restarted every boot.  All that to say that this is less of a worry than it used to be but still happens, and I'm super pleased to hear there are fixes in the works.  Thanks!

**Comment by JakeStanger** [comment]
It will retry and log as fast as your hardware can handle at the moment, so it will add up very quickly. 

Supposedly everything is in place in the discord library, so I'm hoping to get time this weekend to have another look and get it sorted.

**Comment by JakeStanger** [comment]
This is now fully resolved in the latest master. 

I'm waiting on `discord-presence` to get a release out, as this relies on the package's master branch currently.
